# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer-local
field_selection:
  transaction_fields:
    - hash
networks:
  - id: 31337
    start_block: 0
    rpc_config:
      url: http://localhost:8545
    contracts:
      - name: HotPotato
        address:
          - 0x5FbDB2315678afecb367f032d93F642f64180aa3
        handler: src/EventHandlers.ts
        events:
          - event: Claim(address indexed player, uint256 indexed roundId, uint256 amount)
          - event: NewHolder(address indexed holder, uint256 roundId, uint256 newPrice)
          - event: PotUpdated(uint256 newPot)
          - event: RoundEnded(uint256 indexed roundId, uint256 payoutAmount, uint256 numEligible, uint256 potAfter)
          - event: Settle(address indexed player, bool win, uint256 randomness, uint256 roundId)
          - event: SponsorCleared(uint256 indexed roundId)
          - event: SponsorReplaced(address indexed previousSponsor, uint256 refundAmount, uint256 roundId)
          - event: SponsorUpdated(address indexed sponsor, uint256 amount, string message, uint256 roundId)
          - event: Take(address indexed player, uint256 pricePaid, uint256 targetBlock, uint256 roundId)
preload_handlers: true
raw_events: true
